version: '2'

services:

  cp2-ansible-controller-container: #do not change this name or modify kubernetes/DockerFile
    image: charlotron/ansible-controller
    restart: unless-stopped
    privileged: true
    networks:
      vn:
        ipv4_address: 10.10.10.10
    ports:
      - "1010:22"
    volumes:
      - "~/.ssh/id_rsa.pub:/home/ansible/.ssh/authorized_keys.ext"
      - "../ansible:/home/ansible/ansible"
    depends_on:
      - cp2-kubernetes-master-container
      - cp2-kubernetes-worker-container
#      - cp2-nfs

#  #CARE: This image cannot work in a Mac computer nfs modules cannot be enabled for docker engine!!!
#  #This image requires proper modules installed on host machine, execute as root:
#   # modprobe nfs
#   # modprobe nfsd
#  cp2-nfs:
#    image: charlotron/ansible-slave
#    restart: unless-stopped
#    privileged: true
#    cap_add:
#      - SYS_ADMIN
#    networks:
#      vn:
#        ipv4_address: 10.10.10.20
#    ports:
#      - "1020:22"
#    volumes:
#      - "~/.ssh/id_rsa.pub:/home/ansible/.ssh/authorized_keys.ext"
#      - "../nfs/srv:/srv"
#    depends_on:
#      - cp2-kubernetes-master-container

  cp2-kubernetes-master-container:
    image: charlotron/ansible-slave
    restart: unless-stopped
    privileged: true
    networks:
      vn:
        ipv4_address: 10.10.10.100
    ports:
      - "1100:22"
    volumes:
      - "~/.ssh/id_rsa.pub:/home/ansible/.ssh/authorized_keys.ext"

  cp2-kubernetes-worker-container:
    image: charlotron/ansible-slave
    restart: unless-stopped
    privileged: true
    networks:
      vn:
        ipv4_address: 10.10.10.101
    ports:
      - "1101:22"
    volumes:
      - "~/.ssh/id_rsa.pub:/home/ansible/.ssh/authorized_keys.ext"
    depends_on:
      - cp2-kubernetes-master-container



networks:
  vn:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.0/24
          gateway: 10.10.10.1