---

# Check remote mounts: showmount --exports 10.10.10.40

- hosts: nfs
  gather_facts: yes
  tasks:
    - name: Install "nfs-server-kernel" package
      become: true
      apt:
        update_cache: true
        pkg:
         - nfs-kernel-server

    - name: Create mountable dir
      become: true
      file: path=/srv/share state=directory mode=777 owner=root group=root

    - name: Create a test file to check if remote mount worked
      copy:
        dest: "/srv/share/index.html"
        mode: a+x
        content: |
          <!DOCTYPE html>
          <html>
            <head><title>Devops Course - Worked!</title></head>
            <body style="padding:20px;text-align:center;font-family:arial">
                <h1>Devops Course Home</h1>
                <p>This is a sample webpage deployed under kubernetes using ansible on an nginx server.</p><br>
                <img style="margin:40px" src="https://www.freepnglogos.com/uploads/doraemon-png/download-doraemon-png-transparent-image-and-clipart-33.png">
            </body>
          </html>

    - name: Clean exports files (to allow multiple runs)
      become: true
      shell: echo "#==== File generated by ansible from hosts data" > /etc/exports

    - name: (only for local nfs) Create one line for each exports (comment with the name of the host jumpline /srv/share and ip then jumpline)
      become: true
      shell: echo "#{{ item }}\n/srv/share\t{{ hostvars[item].local_ip }}(rw,no_root_squash,no_subtree_check)\n" >> /etc/exports
      loop: "{{ [groups['workers'],groups['master']] | flatten(1) }}" #This takes two lists and unifies them as only one

    - name: Enable service rpcbind
      ansible.builtin.systemd:
        name: rpcbind
        enabled: yes
        masked: no
        state: started

    - name: Enable service nfs-kernel-server
      ansible.builtin.systemd:
        name: nfs-kernel-server
        enabled: yes
        masked: no
        state: started

    - name: Use new configuration of /etc/exports
      become: true
      shell: exportfs -r


- hosts: master:workers
  gather_facts: yes
  tasks:

    - name: Install the "nfs client" package
      become: true
      apt:
        update_cache: true
        pkg:
        - nfs-common

    # The following steps are not needed becouse kubernetes will use a volume provider that will connect via nfs to
    # nfs server directly so this local mount wont be used, but it is usefull to check if nfs comunication is available

    - name: Ensure local dir is not mounted
      become: true
      shell: umount /home/ansible/remote || true

    - name: Preparing remote dir
      file:
        path: /home/ansible/remote
        state: directory
        mode: 0755

    - name: Ensure there is not nfs related lines in fstab
      become: true
      lineinfile: dest=/etc/fstab
                  state=absent
                  search_string="nfs.local"

    - name: Add lines to fstab to mount the remote folder
      become: true
      shell: echo "# Remote mount nfs.local dir /srv/share dir on local /home/ansible/remote \nnfs.local:/srv/share /home/ansible/remote  nfs4      defaults    0       0" >> /etc/fstab

    - name: Automounts fstab mounts
      become: true
      shell: mount -a