---

#To check if pods are linked to this service: "kubectl describe ingress web-ing", under the "Endpoints:" there should be multiple ips corresponding to each service.
#List ingress "kubectl get services -n ingress-nginx" and "kubectl describe service ingress-nginx-controller -n ingress-nginx"

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-ingress
  annotations:
      haproxy.org/path-rewrite: "/"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: "Prefix"
        backend:
          service:
            name: web-svc # This is the value set in service: metadata.name
            port:
              number: 80
