---
#Check all services : kubectl get services -A -o wide

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-ingress
  annotations:
      haproxy.org/path-rewrite: "/"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: "Prefix"
        backend:
          service:
            name: web-svc # This is the value set in service: metadata.name
            port:
              number: 80
      - path: /alsoworks
        pathType: "Prefix"
        backend:
          service:
            name: web-svc # This is the value set in service: metadata.name
            port:
              number: 80

---

kind: Service
apiVersion: v1
metadata:
  name: web-gateway
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30000
  selector:
    name: web-ingress