---
# Connect to a single pod: kubectl exec -ti web-pod-********* -- /bin/sh

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-pod # This is the prefix for the pods generated and displayed by "kubectl get pods" cmd
  labels:
    app: web-pod
spec:
  replicas: 4
  selector:
    matchLabels:
      app: web-pod # This is the value referenced in service: spec.selector
  template:
    metadata:
      labels:
        app: web-pod # This one has to be equals to the spec.selector.matcLabels.app value
    spec:
      containers:
      - name: nginx
        image: nginx:1.17.1-alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: web-site-pvc #This has to be the same as below "volumes.claimName"
          mountPath: /usr/share/nginx/html # This is the static folder
      volumes:
      - name: web-site-pvc
        persistentVolumeClaim:
          claimName: web-nfs-pvc