---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: web-nfs-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: "/srv/share"
    server: "10.10.10.40"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-nfs-pvc
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
